[signet]
name = "signet"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "2.1.1"
rand = "0.8.5"
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
hex = "0.4"
dotenv = "0.15"