[package]
name = "signet"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "2.1.1"
reqwest = { version = "0.12.9", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
hex = "0.4"
dotenv = "0.15"
eth-keystore = "0.5.0"
base32 = "0.4"
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"
crc16 = "0.4.0"
stellar-strkey = "0.0.9"