[package]
name = "local-keystore-to-alloy-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
keystore = { path = "../.." }
alloy-network = "0.9"
alloy-primitives = "0.8"
alloy-signer = "0.9"
alloy-signer-local = "0.9"
